<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Agricultural _1</name>
   <tag></tag>
   <elementGuidId>cab26c60-0caf-405f-9ebe-a3efaf1b6a25</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field CompanyId must be a number.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CompanyId field is required.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShareDetails_1__CompanyId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShareDetails[1].CompanyId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--
Agricultural Development Bank Limited (ADBL)
Api Power Company Limited (API)
Arun Finance Limited (ARUN)
Arun Finance Limited (ARUNPO)
Arun Kabeli Power Limited (AKPL)
Arun Valley Hydropower Development Company Limited (AHPC)
Asian Life Insurance Company Limited (ALICL)
Asian Life Insurance Company Limited (ALICLP)
Bank of Kathmandu Limited (BOKL)
Bank of Kathmandu Limited (BOKLPO)
Barun Hydropower Company Limited (BARUN)
Best Finance Company Ltd. (BFC)
Best Finance Company Ltd. (BFCPO)
Bhargav Bikash Bank Limited (BHBL)
Bhargav Bikash Bank Limited (BHBLPO)
Bishal Bazar Company Limited (BBC)
Bottlers Nepal (Terai) Limited (BNT)
Bottlers Nepal Limited (BNL)
Business Universal Development Bank Limited (BUDBL)
Business Universal Development Bank Limited (BUDBLP)
Butwal Power Company Limited (BPCL)
Central Finance Limited (CFCL)
Central Finance Limited (CFCLPO)
Century Commercial Bank Limited (CCBL)
Century Commercial Bank Limited (CCBLPO)
Chhimek Laghu Bitta Bittiya Sanstha Ltd. (CBBL)
Chhimek Laghu Bitta Bittiya Sanstha Ltd. (CBBLPO)
Chhyangdi Hydropower Limited. (CHL)
Chilime Hydropower Company Limited (CHCL)
Citizen Investment Trust (CIT)
Citizens Bank International Limited (CZBIL)
Citizens Bank International Limited (CZBILP)
Civil Bank Limited (CBL)
Civil Bank Limited (CBLPO)
Civil Laghubitta Bittiya Sanstha Ltd. (CLBSL)
Civil Laghubitta Bittiya Sanstha Ltd. (CLBSLP)
Corporate Development Bank Limited (CORBL)
Corporate Development Bank Limited (CORBLP)
Deprosc Laghubitta Bikas Bank Limited (DDBL)
Deprosc Laghubitta Bikas Bank Limited (DDBLPO)
Deva Bikas Bank Limited (DBBL)
Deva Bikas Bank Limited (DBBLPO)
Dibyashwari Hydropower Limited (DHPL)
Everest Bank Limited (EBL)
Everest Bank Limited (EBLPO)
Everest Bank Limited - Convertible Preference Share (EBLCP)
Everest Insurance Company Limited (EIC)
Excel Development Bank Limited (EDBL)
Excel Development Bank Limited (EDBLPO)
First Microfinance Laghu Bitta Bittiya Sanstha Ltd. (FMDBL)
First Microfinance Laghu Bitta Bittiya Sanstha Ltd. (FMDBLP)
Forward Community Microfinance Bittiya Sanstha Limited. (FOWAD)
Forward Community Microfinance Bittiya Sanstha Limited. (FOWADP)
Gandaki Bikas Bank Limited (GDBL)
Gandaki Bikas Bank Limited (GDBLPO)
Garima Bikas Bank Limited (GBBL)
Garima Bikas Bank Limited (GBBLPO)
Gaumukhee Bikash Bank Limited (GABL)
Global IME Bank Limited (GBIME)
Global IME Bank Limited (GBIMEP)
Global IME Laghubitta Bittiya Sanstha Ltd. (GILB)
Global IME Laghubitta Bittiya Sanstha Ltd. (GILBPO)
Global IME Sammunat Scheme -1 (GIMES1)
Goodwill Finance Limited (GFCL)
Goodwill Finance Limited (GFCLPO)
Green Development Bank Limited (GRDBL)
Green Development Bank Limited (GRDBLP)
Guheswori Merchant Banking &amp; Finance Limited (GMFIL)
Guheswori Merchant Banking &amp; Finance Limited (GMFILP)
Gurans Life Insurance Company Limited (GLICL)
Gurans Life Insurance Company Limited (GLICLP)
Gurkhas Finance Limited (GUFL)
Gurkhas Finance Limited (GUFLPO)
Hamro Bikas Bank Limited (HAMRO)
Hamro Bikas Bank Limited (HAMROP)
Himalayan Bank Limited (HBL)
Himalayan Bank Limited (HBLPO)
HIMALAYAN DISTILLERY LIMITED (HDL)
Himalayan General Insurance Company Limited (HGI)
Himalayan General Insurance Company Limited (HGIPO)
Himalayan Power Partner Limited (HPPL)
ICFC Finance Limited (ICFC)
ICFC Finance Limited (ICFCPO)
IME General Insurance Ltd. (NBIL)
IME General Insurance Ltd. (NBILPO)
International Leasing &amp; Finance Co. Ltd. (ILFC)
International Leasing &amp; Finance Co. Ltd. (ILFCPO)
Jalvidhyut Lagani Tatha Bikas Company Ltd. (HIDCL)
Janaki Finance Limited (JFL)
Janaki Finance Limited (JFLPO)
Janata Bank Nepal Limited (JBNL)
Janata Bank Nepal Limited (JBNLPO)
Janautthan Samudayik Laghubitta Bikash Bank Limited (JSLBB)
Janautthan Samudayik Laghubitta Bikash Bank Limited (JSLBBP)
Jebil's Finance Limited (JEFL)
Jebil's Finance Limited (JEFLPO)
Jyoti Bikash Bank Limited (JBBL)
Jyoti Bikash Bank Limited (JBBLPO)
Kabeli Bikas Bank Limited (KEBL)
Kabeli Bikas Bank Limited (KEBLPO)
Kailash Bikas Bank Limited (KBBL)
Kailash Bikas Bank Limited (KBBLPO)
Kalika Microcredit Development Bank Limited (KMCDB)
Kalika Microcredit Development Bank Limited (KMCDBP)
Kamana Sewa Bikas Bank Limited (KSBBL)
Kamana Sewa Bikas Bank Limited (KSBBLP)
Kanchan Development Bank Limited (KADBL)
Kanchan Development Bank Limited (KADBLP)
Kankai Bikas Bank Limited (KNBL)
Kankai Bikas Bank Limited (KNBLPO)
Karnali Development Bank Limited (KRBL)
Karnali Development Bank Limited (KRBLPO)
Khani Khola Hydropower Company Limited (KKHC)
Kisan Micro Finance Bittiya Sanstha Limited (KMFL)
Kisan Micro Finance Bittiya Sanstha Limited (KMFLPO)
Kuber Merchant Finance Limited (KMBSL)
Kuber Merchant Finance Limited (KMBSLP)
Kumari Bank Limited (KBL)
Kumari Bank Limited (KBLPO)
Lalitpur Finance Limited (LFC)
Lalitpur Finance Limited (LFCPO)
Laxmi Bank Limited (LBL)
Laxmi Bank Limited (LBLPO)
Laxmi Laghubitta Bittiya Sanstha Limited (LLBS)
Laxmi Laghubitta Bittiya Sanstha Limited (LLBSPO)
Laxmi Value Fund-1 (LVF1)
Life Insurance Corporation (Nepal) Ltd. (LICN)
Life Insurance Corporation (Nepal) Ltd. (LICNPO)
Lumbini Bikas Bank Limited (LBBL)
Lumbini Bikas Bank Limited (LBBLPO)
Lumbini General Insurance Company Limited (LGIL)
Lumbini General Insurance Company Limited (LGILPO)
Machhapuchchhre Bank Limited (MBL)
Machhapuchchhre Bank Limited (MBLPO)
Mahalaxmi Bikas Bank Limited (MLBL)
Mahalaxmi Bikas Bank Limited (MLBLPO)
Mahila Sahayatra Microfinance Bittiya Sanstha Limited (MSMBS)
Mahila Sahayatra Microfinance Bittiya Sanstha Limited (MSMBSP)
Mahuli Samudayik Laghubitta Bittiya Sanstha Ltd. (MSLB)
Mahuli Samudayik Laghubitta Bittiya Sanstha Ltd. (MSLBP)
Manjushree Finance Limited (MFIL)
Manjushree Finance Limited (MFILPO)
Mega Bank Nepal Limited (MEGA)
Mega Bank Nepal Limited (MEGAPO)
Mero Microfinance Bittiya Sanstha Limited (MERO)
Mero Microfinance Bittiya Sanstha Limited (MEROPO)
Mirmire Microfinance Development Bank Limited (MMFDB)
Mirmire Microfinance Development Bank Limited (MMFDBP)
Mission Development Bank Limited (MIDBL)
Mission Development Bank Limited (MIDBLP)
Miteri Development Bank Limited (MDB)
Miteri Development Bank Limited (MDBPO)
Mithila Laghubitta Bikash Bank Limited (MLBBL)
Mithila Laghubitta Bikash Bank Limited (MLBBLP)
Mount Makalu Development Bank Limited (MMDBL)
Mount Makalu Development Bank Limited (MMDBLP)
Muktinath Bikas Bank Limited (MNBBL)
Muktinath Bikas Bank Limited (MNBBLP)
Multipurpose Finance Company Ltd. (MPFL)
Multipurpose Finance Company Ltd. (MPFLPO)
Nabil Balanced Fund 1 (NBF1)
Nabil Bank Limited (NABIL)
Nabil Bank Limited (NABILP)
Nabil Equity Fund (NEF)
Nagbeli Laghubitta Bikash Bank Limited (NBBL)
Nagbeli Laghubitta Bikash Bank Limited (NBBLPO)
Namaste Bittiya Sanstha Limited (NBSL)
Namaste Bittiya Sanstha Limited (NBSLPO)
National Hydropower Company Limited (NHPC)
National Life Insurance Company Limited (NLICL)
National Life Insurance Company Limited (NLICLP)
National Microfinance Bittiya Sanstha Ltd. (NMFBS)
National Microfinance Bittiya Sanstha Ltd. (NMFBSP)
Naya Nepal Laghu Bitta Bikas Bank Limited (NNLB)
Naya Nepal Laghu Bitta Bikas Bank Limited (NNLBPO)
Neco Insurance Limited (NIL)
Neco Insurance Limited (NILPO)
Nepal Aawas Finance Limited (NABB)
Nepal Aawas Finance Limited (NABBPO)
Nepal Bangladesh Bank Limited (NBB)
Nepal Bangladesh Bank Limited (NBBPO)
Nepal Bank Limited (NBL)
Nepal Community Development Bank Limited (NCDB)
Nepal Community Development Bank Limited (NCDBPO)
Nepal Credit &amp; Commerce Bank Limited (NCCB)
Nepal Credit &amp; Commerce Bank Limited (NCCBPO)
Nepal Doorsanchar Company Limited (NTC) (NTC)
Grameen Bikas Laghubitta Bittiya Sanstha Limited (GBLBS)
Nepal Grameen Bikas Bank Limited (NGBBLP)
Nepal Hydro Developer Limited (NHDL)
Nepal Insurance Company Ltd. (NICL)
Nepal Insurance Company Ltd. (NICLPO)
Nepal Investment Bank Limited (NIB)
Nepal Investment Bank Limited (NIBPO)
Nepal Life Insurance Company Limited (NLIC)
Nepal Life Insurance Company Limited (NLICP)
Nepal SBI Bank Limited (SBI)
Nepal SBI Bank Limited (SBIPO)
Nerude Laghubitta Bikas Bank Limited (NLBBL)
Nerude Laghubitta Bikas Bank Limited (NLBBLP)
Ngadi Group Power Limited (NGPL)
NIBL Pragati Fund (NIBLPF)
NIBL Samriddhi Fund -1 (NIBSF1)
NIC Asia Bank Limited (NICA)
NIC Asia Bank Limited (NICAP)
NIDC Development Bank Limited (NIDC)
NIDC Development Bank Limited (NIDCPO)
Nirdhan Utthan Bank Limited (NUBL)
Nirdhan Utthan Bank Limited (NUBLPO)
NLG Insurance Company Limited (NLG)
NLG Insurance Company Limited (NLGPO)
NMB Bank Limited (NMB)
NMB Bank Limited (NMBPO)
NMB Hybrid Fund L- 1 (NMBHFL1)
NMB Microfinance Bittiya Sanstha Limited (NMBMF)
NMB Microfinance Bittiya Sanstha Limited (NMBMFP)
NMB Sulav Investment Fund - I (NMBSF1)
Om Development Bank Limited (ODBL)
Om Development Bank Limited (ODBLPO)
Oriental Hotels Limited (OHL)
Pokhara Finance Limited (PFL)
Pokhara Finance Limited (PFLPO)
Prabhu Bank Limited (PRVU)
Prabhu Bank Limited (PRVUPO)
Prabhu Insurance Limited (PRIN)
Prabhu Insurance Limited (PRINPO)
Premier Insurance Company (Nepal) Limited (PIC)
Premier Insurance Company (Nepal) Limited (PICPO)
Prime Commercial Bank Limited (PCBL)
Prime Commercial Bank Limited (PCBLP)
Primelife Insurance Company Limited (PLIC)
Primelife Insurance Company Limited (PLICPO)
Progressive Finance Limited (PROFL)
Progressive Finance Limited (PROFLP)
Prudential Insurance Company Limited (PICL)
Prudential Insurance Company Limited (PICLPO)
Purnima Bikas Bank Limited (PURBL)
Purnima Bikas Bank Limited (PURBLP)
Radhi Bidyut Company Ltd. (RADHI)
Rastriya Beema Company Limited (RBCL)
Rastriya Beema Company Limited (RBCLPO)
Reliance Finance Limited (RLFL)
Reliance Finance Limited (RLFLPO)
Ridi Hydropower Development Company Limited (RHPC)
RSDC Laghubitta Bittiya Sanstha Limited (RSDC)
RSDC Laghubitta Bittiya Sanstha Limited (RSDCP)
Rural Microfinance Development Centre Limited (RMDC)
Rural Microfinance Development Centre Limited (RMDCPO)
Sagarmatha Insurance Company Limited (SIC)
Sagarmatha Insurance Company Limited (SICPO)
Sahara Bikash Bank Limited (SHBL)
Sahara Bikash Bank Limited (SHBLPO)
Sahayogi Vikas Bank Limited (SBBLJ)
Sahayogi Vikas Bank Limited (SBBLJP)
Salt Trading Corporation Limited (STC)
Samata Microfinance Bittiya Sanstha Limited (SMATA)
Samata Microfinance Bittiya Sanstha Limited (SMATAP)
Sana Kisan Bikas Bank Limited (SKBBL)
Sana Kisan Bikas Bank Limited (SKBBLP)
Sanima Bank Limited (SANIMA)
Sanima Bank Limited (SBBLPO)
Sanima Equity Fund (SAEF)
Sanima Mai Hydropower Limited (SHPC)
Saptakoshi Development Bank Limited (SKDBL)
Saptakoshi Development Bank Limited (SKDBLP)
Shangrila Development Bank Limited (SADBL)
Shangrila Development Bank Limited (SADBLP)
Shikhar Insurance Company Ltd. (SICL)
Shikhar Insurance Company Ltd. (SICLPO)
Shine Resunga Development Bank Limited (SHINE)
Shine Resunga Development Bank Limited (SHINEP)
Shree Investment and Finance Company Ltd. (SIFC)
Shree Investment and Finance Company Ltd. (SIFCPO)
Siddhartha Bank Limited (SBL)
Siddhartha Bank Limited (SBLPO)
Siddhartha Equity Fund (SEF)
Siddhartha Equity Oriented Scheme (SEOS)
Siddhartha Insurance Limited (SIL)
Siddhartha Insurance Limited (SILPO)
Siddhartha Investment Growth Scheme-1 (SIGS1)
Sindhu Bikash Bank Limited (SINDU)
Sindhu Bikash Bank Limited (SINDUP)
Soaltee Hotel Limited (SHL)
Sri Ram Sugar Mills Limited (SRS)
Srijana Finance Limited (SFFIL)
Srijana Finance Limited (SFFILP)
Standard Chartered Bank Nepal Limited (SCB)
Standard Chartered Bank Nepal Limited (SCBPO)
Summit Microfinance Development Bank Limited (SMFDB)
Summit Microfinance Development Bank Limited (SMFDBP)
Sunrise Bank Limited (SRBL)
Sunrise Bank Limited (SRBLPO)
Support Microfinance Bittiya Sanstha Ltd. (SMB)
Support Microfinance Bittiya Sanstha Ltd. (SMBPO)
Surya Life Insurance Company Limited (SLICL)
Surya Life Insurance Company Limited (SLICLP)
Suryodaya Laghubitta Bittiya Sanstha Ltd. (SLBS)
Suryodaya Laghubitta Bittiya Sanstha Ltd. (SLBSP)
Swabalamban Laghubitta Bikas Bank Limited (SWBBL)
Swabalamban Laghubitta Bikas Bank Limited (SWBBLP)
Swadeshi Laghubitta Bittiya Sanstha Ltd. (SDESI)
Swadeshi Laghubitta Bittiya Sanstha Ltd. (SDESIP)
Swarojgar Laghubitta Bikas Bank Limited (SLBBL)
Swarojgar Laghubitta Bikas Bank Limited (SLBBLP)
Synergy Finance Limited (SYFL)
Synergy Finance Limited (SYFLPO)
Synergy Power Development Limited (SPDL)
Taragaon Regency Hotels Limited (TRH)
Tinau Development Bank Limited (TNBL)
Tinau Development Bank Limited (TNBLPO)
Tourism Development Bank Limited (TDBL)
Tourism Development Bank Limited (TDBLPO)
Unilever Nepal Limited (UNL)
United Finance Limited (UFL)
United Finance Limited (UFLPO)
United Insurance Company (Nepal) Limited (UIC)
United Insurance Company (Nepal) Limited (UICPO)
United Modi Hydropower Limited (UMHL)
Unnati Microfinance Bittiya Sanstha Ltd. (UMBPO)
Unnati Microfinance Bittiya Sanstha Ltd. (UMB)
Vijaya Laghubitta Bittiya Sanstha Limited (VLBS)
Vijaya Laghubitta Bittiya Sanstha Limited (VLBSPO)
Western Development Bank Limited (WDBL)
Western Development Bank Limited (WDBLPO)
Womi Microfinance Bittiya Sanstha Limited (WOMI)
Womi Microfinance Bittiya Sanstha Limited (WOMIPO)
World Merchant Banking and Finance Limited. (WMBF)
World Merchant Banking and Finance Limited. (WMBFPO)
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShareDetails_1__CompanyId&quot;)</value>
   </webElementProperties>
</WebElementEntity>
