<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_glyphicon glyphicon-plus Dyn_1</name>
   <tag></tag>
   <elementGuidId>aa1232ad-3b88-465f-a3b5-f0d7bc14fa8e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-type</name>
      <type>Main</type>
      <value>RelatedPersonFamily</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-display</name>
      <type>Main</type>
      <value>Related Person Family</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bail-id</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-method</name>
      <type>Main</type>
      <value>add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-container</name>
      <type>Main</type>
      <value>tr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-plus DynamicDivUpdate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RelatedPerson&quot;)/div[@class=&quot;RelatedPersonSingle&quot;]/div[1]/div[@class=&quot;relatedPersonDetail&quot;]/div[6]/div[1]/span[@class=&quot;addUpdateIconDiv&quot;]/a[@class=&quot;glyphicon glyphicon-plus DynamicDivUpdate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
