<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- select --AchhamArgha</name>
   <tag></tag>
   <elementGuidId>166fa973-d936-44c3-b877-dcec31649400</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The District field is required.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PersonalDetail_PermanentAddress_District</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PersonalDetail.PermanentAddress.District</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- select --
Achham
Arghakhanchi
Baglung
Baitadi
Bajhang
Bajura
Banke
Bara
Bardiya
Bhaktapur
Bhojpur
Chitwan
Dadeldhura
Dailekh
Dang Deukhuri
Darchula
Dhading
Dhankuta
Dhanusa
Dolakha
Dolpa
Doti
Gorkha
Gulmi
Humla
Ilam
Jajarkot
Jhapa
Jumla
Kailali
Kalikot
Kanchanpur
Kapilvastu
Kaski
Kathmandu
Kavrepalanchok
Khotang
Lalitpur
Lamjung
Mahottari
Makwanpur
Manang
Morang
Mugu
Mustang
Myagdi
Nawalparasi
Nuwakot
Okhaldhunga
Palpa
Panchthar
Parbat
Parsa
Pyuthan
Ramechhap
Rasuwa
Rautahat
Rolpa
Rukum
Rupandehi
Salyan
Sankhuwasabha
Saptari
Sarlahi
Sindhuli
Sindhupalchok
Siraha
Solukhumbu
Sunsari
Surkhet
Syangja
Tanahun
Taplejung
Terhathum
Udayapur
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PersonalDetail_PermanentAddress_District&quot;)</value>
   </webElementProperties>
</WebElementEntity>
